data:
  fraction: 0.25  # Use 25% of the dataset for faster experimentation
  seed: 42        # Random seed for reproducibility

train:
  learning_rate: 0.001
  batch_size: 32
  epochs: 10
  model_name: "resnet18"  # Options: resnet18, resnet34, resnet50, efficientnet_b0, etc.
  optimizer: "adam"       # Options: adam, sgd
  weight_decay: 0.0001
  num_workers: 4

evaluate:
  checkpoint_path: "models/model.pth"
  data_path: "data"
  batch_size: 32
  num_workers: 4
  metrics_output: "reports/eval_metrics.json"
